export const ghostNames = [
  "Banshee",
  "Demon",
  "Hantu",
  "Jinn",
  "Mare",
  "Oni",
  "Phantom",
  "Poltergeist",
  "Revenant",
  "Shade",
  "Spirit",
  "Wraith",
  "Yokai",
  "Yurei",
];

export const ghosts = [
  {
    id: "banshee",
    i18nKey: "phasmo.ghosts.banshee",
    evidence: ["ghostorbs", "fingerprints", "dotsprojector"],
    secondaryEvidencei18nKeys: ["banshee1"],
  },
  {
    id: "demon",
    i18nKey: "phasmo.ghosts.demon",
    evidence: ["ghostwriting", "freezingtemperatures", "fingerprints"],
    secondaryEvidencei18nKeys: ["demon1", "demon2"],
  },
  {
    id: "goryo",
    i18nKey: "phasmo.ghosts.goryo",
    name: "Goryo",
    evidence: ["emflevel5", "fingerprints", "dotsprojector"],
    secondaryEvidencei18nKeys: ["goryo1"],
  },
  {
    id: "hantu",
    i18nKey: "phasmo.ghosts.hantu",
    name: "Hantu",
    evidence: ["fingerprints", "ghostorbs", "freezingtemperatures"],
    secondaryEvidencei18nKeys: [],
  },
  {
    id: "jinn",
    i18nKey: "phasmo.ghosts.jinn",
    name: "Jinn",
    evidence: ["emflevel5", "freezingtemperatures", "fingerprints"],
    secondaryEvidencei18nKeys: ["jinn1", "jinn2"],
  },
  {
    id: "mare",
    i18nKey: "phasmo.ghosts.mare",
    name: "Mare",
    evidence: ["ghostwriting", "ghostorbs", "spiritbox"],
    secondaryEvidencei18nKeys: ["mare1", "mare2", "mare3"],
  },
  {
    id: "myling",
    i18nKey: "phasmo.ghosts.myling",
    name: "Myling",
    evidence: ["emflevel5", "fingerprints", "ghostwriting"],
    secondaryEvidencei18nKeys: ["myling1"],
  },
  {
    id: "oni",
    i18nKey: "phasmo.ghosts.oni",
    name: "Oni",
    evidence: ["emflevel5", "freezingtemperatures", "dotsprojector"],
    secondaryEvidencei18nKeys: ["oni1"],
  },
  {
    id: "phantom",
    i18nKey: "phasmo.ghosts.phantom",
    name: "Phantom",
    evidence: ["spiritbox", "fingerprints", "dotsprojector"],
    secondaryEvidencei18nKeys: ["phantom1", "phantom2"],
  },
  {
    id: "poltergeist",
    i18nKey: "phasmo.ghosts.poltergeist",
    name: "Poltergeist",
    evidence: ["ghostwriting", "spiritbox", "fingerprints"],
    secondaryEvidencei18nKeys: ["poltergeist1"],
  },
  {
    id: "revenant",
    i18nKey: "phasmo.ghosts.revenant",
    name: "Revenant",
    evidence: ["ghostorbs", "ghostwriting", "freezingtemperatures"],
    secondaryEvidencei18nKeys: ["revenant1", "revenant2"],
  },
  {
    id: "shade",
    name: "Shade",
    i18nKey: "phasmo.ghosts.shade",
    evidence: ["emflevel5", "freezingtemperatures", "ghostwriting"],
    secondaryEvidencei18nKeys: [],
  },
  {
    id: "spirit",
    i18nKey: "phasmo.ghosts.spirit",
    name: "Spirit",
    evidence: ["emflevel5", "ghostwriting", "spiritbox"],
    secondaryEvidencei18nKeys: ["spirit1"],
  },
  {
    id: "wraith",
    i18nKey: "phasmo.ghosts.wraith",
    name: "Wraith",
    evidence: ["emflevel5", "dotsprojector", "spiritbox"],
    secondaryEvidencei18nKeys: ["wraith1"],
  },
  {
    id: "yokai",
    i18nKey: "phasmo.ghosts.yokai",
    name: "Yokai",
    evidence: ["ghostorbs", "dotsprojector", "spiritbox"],
    secondaryEvidencei18nKeys: [],
  },
  {
    id: "yurei",
    i18nKey: "phasmo.ghosts.yurei",
    name: "Yurei",
    evidence: ["freezingtemperatures", "ghostorbs", "dotsprojector"],
    secondaryEvidencei18nKeys: [],
  },
];

const allGhosts = ghosts.map((ghost) => ({
  ...ghost,
  included: true,
}));

export const initialState = {
  list: allGhosts,
  selected: null,
  visible: true,
};
