export const GHOST_NAMES = {
  firstnames: [
    "Charles",
    "Christopher",
    "Daniel",
    "David",
    "Donald",
    "George",
    "James",
    "John",
    "Joseph",
    "Kenneth",
    "Mark",
    "Michael",
    "Paul",
    "Richard",
    "Robert",
    "Steven",
    "Thomas",
    "William",
    "Barbara",
    "Betty",
    "Carol",
    "Donna",
    "Dorothy",
    "Elizabeth",
    "Helen",
    "Jennifer",
    "Karen",
    "Linda",
    "Lisa",
    "Margaret",
    "Maria",
    "Mary",
    "Nancy",
    "Patricia",
    "Ruth",
    "Sandra",
    "Susan",
  ],
  lastnames: [
    "Anderson",
    "Brown",
    "Clark",
    "Davis",
    "Garcia",
    "Harris",
    "Jackson",
    "Johnson",
    "Jones",
    "Martin",
    "Martinez",
    "Miller",
    "Moore",
    "Robinson",
    "Smith",
    "Taylor",
    "Thomas",
    "Thompson",
    "Williams",
    "Wilson",
    "White",
  ],
};

export const FIRSTNAME_FIRST_LETTERS = [
  ...new Set(GHOST_NAMES.firstnames.map((name) => name.slice(0, 1))),
].sort();
export const LASTNAME_FIRST_LETTERS = [
  ...new Set(GHOST_NAMES.lastnames.map((name) => name.slice(0, 1))),
].sort();

export const HEADER_TEXT = {
  first: "Select First Letter of Ghost's First Name",
  second: "Select Ghost's First Name",
  third: "Select First Letter of Ghost's Last Name",
  fourth: "Select Ghost's Last Name",
  fifth: "Ghost Name",
};

export const initialState = {
  ref: {
    firstnames: GHOST_NAMES.firstnames,
    lastnames: GHOST_NAMES.lastnames,
  },
  firstnames: [],
  lastnames: [],
  firstnameLetters: FIRSTNAME_FIRST_LETTERS,
  lastnameLetters: LASTNAME_FIRST_LETTERS,
  firstname: "",
  lastname: "",
  fullname: "",
  views: {
    firstnameLetters: true,
    firstnames: false,
    lastnameLetters: false,
    firstname: false,
    lastname: false,
    lastnames: false,
    fullname: false,
  },
};

export const falseViews = {
  firstnameLetters: false,
  firstnames: false,
  lastnameLetters: false,
  firstname: false,
  lastname: false,
  lastnames: false,
  fullname: false,
};
